In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from itertools import product
import torch.nn as nn
import torch
import torch.nn.functional as F

In [3]:
# imports from this project
from ransacflow.model import FeatureExtractor

In [4]:
kernelSize = 7
imageSize = 224
batchSize = 1


In [32]:
feature_extractor = FeatureExtractor()

f1 = feature_extractor(I1)
print(f1.shape)

torch.Size([1, 256, 28, 28])


In [5]:
f1 = torch.randint(1, 28+1, (256, 28, 28), dtype=torch.float32)
f1 = f1.unsqueeze(dim=0)
print(f1.shape)

torch.Size([1, 256, 28, 28])


In [17]:
%%timeit -n 3 -r 3

x = y = F.normalize(f1)

paddingSize = kernelSize // 2
padding = nn.ZeroPad2d(paddingSize)

w, h = x.size()[2:]
coef = []
y = padding(y)

for i, j in product(range(kernelSize), range(kernelSize)):
    #print(f"i={i}, j={j}")
    coef.append(torch.sum(x * y.narrow(2, i, w).narrow(3, j, h), dim=1, keepdim=True))
coef = torch.cat(coef, dim=1)
print(coef.shape)
print(coef[0, :5, 3, 3])

torch.Size([1, 49, 28, 28])
tensor([0.7750, 0.7849, 0.8007, 0.7930, 0.7988])
torch.Size([1, 49, 28, 28])
tensor([0.7750, 0.7849, 0.8007, 0.7930, 0.7988])
torch.Size([1, 49, 28, 28])
tensor([0.7750, 0.7849, 0.8007, 0.7930, 0.7988])
torch.Size([1, 49, 28, 28])
tensor([0.7750, 0.7849, 0.8007, 0.7930, 0.7988])
torch.Size([1, 49, 28, 28])
tensor([0.7750, 0.7849, 0.8007, 0.7930, 0.7988])
torch.Size([1, 49, 28, 28])
tensor([0.7750, 0.7849, 0.8007, 0.7930, 0.7988])
torch.Size([1, 49, 28, 28])
tensor([0.7750, 0.7849, 0.8007, 0.7930, 0.7988])
torch.Size([1, 49, 28, 28])
tensor([0.7750, 0.7849, 0.8007, 0.7930, 0.7988])
torch.Size([1, 49, 28, 28])
tensor([0.7750, 0.7849, 0.8007, 0.7930, 0.7988])
4.55 ms ± 296 µs per loop (mean ± std. dev. of 3 runs, 3 loops each)


In [21]:
%%timeit -n 3 -r 3

from ransacflow.model import NeighborCorrelator

corr = NeighborCorrelator(7)

coef2 = corr(f1, f1)
print(coef2.shape)
print(coef[0, :5, 3, 3])

torch.Size([1, 49, 28, 28])
tensor([0.7750, 0.7849, 0.8007, 0.7930, 0.7988])
torch.Size([1, 49, 28, 28])
tensor([0.7750, 0.7849, 0.8007, 0.7930, 0.7988])
torch.Size([1, 49, 28, 28])
tensor([0.7750, 0.7849, 0.8007, 0.7930, 0.7988])
torch.Size([1, 49, 28, 28])
tensor([0.7750, 0.7849, 0.8007, 0.7930, 0.7988])
torch.Size([1, 49, 28, 28])
tensor([0.7750, 0.7849, 0.8007, 0.7930, 0.7988])
torch.Size([1, 49, 28, 28])
tensor([0.7750, 0.7849, 0.8007, 0.7930, 0.7988])
torch.Size([1, 49, 28, 28])
tensor([0.7750, 0.7849, 0.8007, 0.7930, 0.7988])
torch.Size([1, 49, 28, 28])
tensor([0.7750, 0.7849, 0.8007, 0.7930, 0.7988])
torch.Size([1, 49, 28, 28])
tensor([0.7750, 0.7849, 0.8007, 0.7930, 0.7988])
The slowest run took 4.07 times longer than the fastest. This could mean that an intermediate result is being cached.
11.7 ms ± 8.08 ms per loop (mean ± std. dev. of 3 runs, 3 loops each)
