In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch

In [4]:
kernelSize = 7
imageSize = 224
batchSize = 1

paddingSize = kernelSize // 2

In [27]:
from torchsummary import summary

In [31]:
I = torch.empty((49, 28, 28))


In [51]:
from ransacflow.model.model_orig import NetFlow
m1 = NetFlow(7, 'netFlowCoarse').cuda()
summary(m1, I.shape)

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1          [-1, 512, 28, 28]         225,792
       BatchNorm2d-2          [-1, 512, 28, 28]           1,024
              ReLU-3          [-1, 512, 28, 28]               0
            Conv2d-4          [-1, 256, 28, 28]       1,179,648
       BatchNorm2d-5          [-1, 256, 28, 28]             512
              ReLU-6          [-1, 256, 28, 28]               0
            Conv2d-7          [-1, 128, 28, 28]         294,912
       BatchNorm2d-8          [-1, 128, 28, 28]             256
              ReLU-9          [-1, 128, 28, 28]               0
           Conv2d-10           [-1, 49, 28, 28]          56,448
          Softmax-11           [-1, 49, 28, 28]               0
Total params: 1,758,592
Trainable params: 1,758,592
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.15
Forw

/home/andy/.conda/envs/ransacflow/lib/python3.8/site-packages/torch/nn/functional.py:3847: UserWarning: nn.functional.upsample_bilinear is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample_bilinear is deprecated. Use nn.functional.interpolate instead.")


In [49]:
from ransacflow.model import FlowPredictor, MatchabilityPredictor
m2 = FlowPredictor(224, 7).cuda()
summary(m2, I.shape)

x.shape=torch.Size([2, 49, 28, 28])
grid_x.shape=torch.Size([1, 49, 1, 1])
flow_x.shape=torch.Size([2, 1, 28, 28])
x.shape=torch.Size([2, 2, 28, 28])
----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1          [-1, 512, 28, 28]         225,792
       BatchNorm2d-2          [-1, 512, 28, 28]           1,024
              ReLU-3          [-1, 512, 28, 28]               0
            Conv2d-4          [-1, 256, 28, 28]       1,179,648
       BatchNorm2d-5          [-1, 256, 28, 28]             512
              ReLU-6          [-1, 256, 28, 28]               0
            Conv2d-7          [-1, 128, 28, 28]         294,912
       BatchNorm2d-8          [-1, 128, 28, 28]             256
              ReLU-9          [-1, 128, 28, 28]               0
           Conv2d-10           [-1, 49, 28, 28]          56,448
          Softmax-11           [-1, 49, 28, 28]               0
Total params: 1,7

In [2]:
import numpy as np

batchSize = 3
index = np.arange(batchSize * 2)
print(index)
indexRoll = np.roll(index, batchSize)
print(indexRoll)


[0 1 2 3 4 5]
[3 4 5 0 1 2]


In [4]:
import torch

In [9]:
imgSize = 5
gridY = (
    torch.linspace(-1, 1, steps=imgSize)
    .view(1, -1, 1, 1)
    .expand(1, imgSize, imgSize, 1)
)
gridX = (
    torch.linspace(-1, 1, steps=imgSize)
    .view(1, 1, -1, 1)
    .expand(1, imgSize, imgSize, 1)
)
grid = torch.cat((gridX, gridY), dim=3).cuda()


In [6]:
grid.shape

torch.Size([1, 4, 4, 2])

In [11]:
grid[..., 0]

tensor([[[-1.0000, -0.5000,  0.0000,  0.5000,  1.0000],
         [-1.0000, -0.5000,  0.0000,  0.5000,  1.0000],
         [-1.0000, -0.5000,  0.0000,  0.5000,  1.0000],
         [-1.0000, -0.5000,  0.0000,  0.5000,  1.0000],
         [-1.0000, -0.5000,  0.0000,  0.5000,  1.0000]]], device='cuda:0')

In [16]:
vx = torch.linspace(-1, 1, imgSize)
vy = torch.linspace(-1, 1, imgSize)
grid_x, grid_y = torch.meshgrid(vx, vy, indexing="xy")
grid2 = torch.stack([grid_x, grid_y], dim=-1)
grid2[..., 0]

tensor([[-1.0000, -0.5000,  0.0000,  0.5000,  1.0000],
        [-1.0000, -0.5000,  0.0000,  0.5000,  1.0000],
        [-1.0000, -0.5000,  0.0000,  0.5000,  1.0000],
        [-1.0000, -0.5000,  0.0000,  0.5000,  1.0000],
        [-1.0000, -0.5000,  0.0000,  0.5000,  1.0000]])

In [ ]:
batch = [
    (("A1", [11]), ("B1", [21]), [31]),
    (("A2", [12]), ("B2", [22]), [32]),
    (("A3", [13]), ("B3", [23]), [33]),
]

